package org.openimaj.hardware.kinect.freenect;

import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * <i>native declaration : /usr/include/stdint.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("freenect-combined")
@SuppressWarnings("all")
public class freenect_registration extends StructObject {
	public freenect_registration() {
		super();
	}
	/// C type : freenect_reg_info
	@Field(0) 
	public freenect_reg_info reg_info() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : freenect_reg_info
	@Field(0) 
	public freenect_registration reg_info(freenect_reg_info reg_info) {
		this.io.setNativeObjectField(this, 0, reg_info);
		return this;
	}
	/// C type : freenect_reg_pad_info
	@Field(1) 
	public freenect_reg_pad_info reg_pad_info() {
		return this.io.getNativeObjectField(this, 1);
	}
	/// C type : freenect_reg_pad_info
	@Field(1) 
	public freenect_registration reg_pad_info(freenect_reg_pad_info reg_pad_info) {
		this.io.setNativeObjectField(this, 1, reg_pad_info);
		return this;
	}
	/// C type : freenect_zero_plane_info
	@Field(2) 
	public freenect_zero_plane_info zero_plane_info() {
		return this.io.getNativeObjectField(this, 2);
	}
	/// C type : freenect_zero_plane_info
	@Field(2) 
	public freenect_registration zero_plane_info(freenect_zero_plane_info zero_plane_info) {
		this.io.setNativeObjectField(this, 2, zero_plane_info);
		return this;
	}
	@Field(3) 
	public double const_shift() {
		return this.io.getDoubleField(this, 3);
	}
	@Field(3) 
	public freenect_registration const_shift(double const_shift) {
		this.io.setDoubleField(this, 3, const_shift);
		return this;
	}
	/// C type : uint16_t*
	@Field(4) 
	public Pointer<Short > raw_to_mm_shift() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : uint16_t*
	@Field(4) 
	public freenect_registration raw_to_mm_shift(Pointer<Short > raw_to_mm_shift) {
		this.io.setPointerField(this, 4, raw_to_mm_shift);
		return this;
	}
	/// C type : int32_t*
	@Field(5) 
	public Pointer<Integer > depth_to_rgb_shift() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : int32_t*
	@Field(5) 
	public freenect_registration depth_to_rgb_shift(Pointer<Integer > depth_to_rgb_shift) {
		this.io.setPointerField(this, 5, depth_to_rgb_shift);
		return this;
	}
	/**
	 * A table of 640*480 pairs of x,y values.<br>
	 * C type : int32_t[2]*
	 */
	@Field(6) 
	public Pointer<Pointer<Integer > > registration_table() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * A table of 640*480 pairs of x,y values.<br>
	 * C type : int32_t[2]*
	 */
	@Field(6) 
	public freenect_registration registration_table(Pointer<Pointer<Integer > > registration_table) {
		this.io.setPointerField(this, 6, registration_table);
		return this;
	}
}
