/**
 * Copyright (c) 2011, The University of Southampton and the individual contributors.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *   * 	Redistributions of source code must retain the above copyright notice,
 * 	this list of conditions and the following disclaimer.
 *
 *   *	Redistributions in binary form must reproduce the above copyright notice,
 * 	this list of conditions and the following disclaimer in the documentation
 * 	and/or other materials provided with the distribution.
 *
 *   *	Neither the name of the University of Southampton nor the names of its
 * 	contributors may be used to endorse or promote products derived from this
 * 	software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.openimaj.hardware.kinect.freenect;

import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/include/stdint.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@SuppressWarnings("all")
@Library("freenect-combined")
public class freenect_zero_plane_info extends StructObject {
	public freenect_zero_plane_info() {
		super();
	}
	/// Distance between IR camera and IR emitter, in cm.
	@Field(0) 
	public float dcmos_emitter_dist() {
		return this.io.getFloatField(this, 0);
	}
	/// Distance between IR camera and IR emitter, in cm.
	@Field(0) 
	public freenect_zero_plane_info dcmos_emitter_dist(float dcmos_emitter_dist) {
		this.io.setFloatField(this, 0, dcmos_emitter_dist);
		return this;
	}
	/// Distance between IR camera and RGB camera, in cm.
	@Field(1) 
	public float dcmos_rcmos_dist() {
		return this.io.getFloatField(this, 1);
	}
	/// Distance between IR camera and RGB camera, in cm.
	@Field(1) 
	public freenect_zero_plane_info dcmos_rcmos_dist(float dcmos_rcmos_dist) {
		this.io.setFloatField(this, 1, dcmos_rcmos_dist);
		return this;
	}
	/// The focal length of the IR camera, in mm.
	@Field(2) 
	public float reference_distance() {
		return this.io.getFloatField(this, 2);
	}
	/// The focal length of the IR camera, in mm.
	@Field(2) 
	public freenect_zero_plane_info reference_distance(float reference_distance) {
		this.io.setFloatField(this, 2, reference_distance);
		return this;
	}
	/// The size of a single pixel on the zero plane, in mm.
	@Field(3) 
	public float reference_pixel_size() {
		return this.io.getFloatField(this, 3);
	}
	/// The size of a single pixel on the zero plane, in mm.
	@Field(3) 
	public freenect_zero_plane_info reference_pixel_size(float reference_pixel_size) {
		this.io.setFloatField(this, 3, reference_pixel_size);
		return this;
	}
}
