package org.openimaj.hardware.kinect.freenect;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/include/stdint.h:285</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("freenect") 
public class freenect_device_attributes extends StructObject {
	public freenect_device_attributes() {
		super();
	}
	/**
	 * < Next device in the linked list<br>
	 * C type : freenect_device_attributes*
	 */
	@Field(0) 
	public Pointer<freenect_device_attributes > next() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * < Next device in the linked list<br>
	 * C type : freenect_device_attributes*
	 */
	@Field(0) 
	public freenect_device_attributes next(Pointer<freenect_device_attributes > next) {
		this.io.setPointerField(this, 0, next);
		return this;
	}
	/**
	 * < Serial number of this device's camera subdevice<br>
	 * C type : const char*
	 */
	@Field(1) 
	public Pointer<Byte > camera_serial() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * < Serial number of this device's camera subdevice<br>
	 * C type : const char*
	 */
	@Field(1) 
	public freenect_device_attributes camera_serial(Pointer<Byte > camera_serial) {
		this.io.setPointerField(this, 1, camera_serial);
		return this;
	}
}