package org.openimaj.hardware.kinect.freenect;

import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/include/stdint.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@SuppressWarnings("all")
@Library("freenect-combined")
public class freenect_zero_plane_info extends StructObject {
	public freenect_zero_plane_info() {
		super();
	}
	/// Distance between IR camera and IR emitter, in cm.
	@Field(0) 
	public float dcmos_emitter_dist() {
		return this.io.getFloatField(this, 0);
	}
	/// Distance between IR camera and IR emitter, in cm.
	@Field(0) 
	public freenect_zero_plane_info dcmos_emitter_dist(float dcmos_emitter_dist) {
		this.io.setFloatField(this, 0, dcmos_emitter_dist);
		return this;
	}
	/// Distance between IR camera and RGB camera, in cm.
	@Field(1) 
	public float dcmos_rcmos_dist() {
		return this.io.getFloatField(this, 1);
	}
	/// Distance between IR camera and RGB camera, in cm.
	@Field(1) 
	public freenect_zero_plane_info dcmos_rcmos_dist(float dcmos_rcmos_dist) {
		this.io.setFloatField(this, 1, dcmos_rcmos_dist);
		return this;
	}
	/// The focal length of the IR camera, in mm.
	@Field(2) 
	public float reference_distance() {
		return this.io.getFloatField(this, 2);
	}
	/// The focal length of the IR camera, in mm.
	@Field(2) 
	public freenect_zero_plane_info reference_distance(float reference_distance) {
		this.io.setFloatField(this, 2, reference_distance);
		return this;
	}
	/// The size of a single pixel on the zero plane, in mm.
	@Field(3) 
	public float reference_pixel_size() {
		return this.io.getFloatField(this, 3);
	}
	/// The size of a single pixel on the zero plane, in mm.
	@Field(3) 
	public freenect_zero_plane_info reference_pixel_size(float reference_pixel_size) {
		this.io.setFloatField(this, 3, reference_pixel_size);
		return this;
	}
}
