package openimajgrabber;

import java.util.ArrayList;
import java.util.List;

import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.cpp.CPPObject;

/**
 * <i>native declaration : line 1</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("OpenIMAJGrabber") 
public class DeviceList extends CPPObject {
	public DeviceList() {
		super();
	}
	
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public DeviceList(Pointer pointer) {
		super(pointer);
	}
	
	public native int getNumDevices();
	public native Pointer<Device> getDevice(int i);

	public List<Device> asArrayList() {
		List<Device> devices = new ArrayList<Device>();
		
		for (int i=0; i<getNumDevices(); i++) {
			devices.add(getDevice(i).get());
		}
		
		return devices;
	}
}
