package org.openimaj.text.nlp.textpipe.annotations;

/**
 * A {@link TokenAnnotation} represents a single token generated by a tokeniser.
 * It can be further annotated. It is aware of its off-sets in the
 * RawStringAnnotation that generated it.
 * 
 * @author laurence
 * 
 */
public class TokenAnnotation extends TextPipeAnnotation {
	String stringToken;
	public int start;
	public int stop;

	public TokenAnnotation(String raw, int start, int stop) {
		super();
		this.stringToken = raw;
		this.start = start;
		this.stop = stop;
	}

	public String getStringToken() {
		return stringToken;
	}

}
