#!/bin/bash

# A simple shell script to run the FaceRecogniserTrainingTool
#
# @author Jonathon Hare

bin=`dirname "$0"`

java -Xmx2G -Djava.awt.headless=true -cp "$bin/target/FaceTools.jar" org.openimaj.tools.faces.recognition.FaceRecogniserTrainingTool ${1+"$@"}
