PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX sioct: <http://rdfs.org/sioc/types#>
PREFIX dcns: <http://purl.org/dc/elements/1.1/>
PREFIX dctermsns: <http://purl.org/dc/terzms/>
PREFIX dctypens: <http://purl.org/dc/dcmitype/>
PREFIX dcamns: <http://purl.org/dc/dcam/>
PREFIX tm: <http://www.trendminer-project.eu/ontology/>

SELECT *
WHERE {
	?socialEvent a sioc:Item.
	OPTIONAL ?socialEvent sioc:container ?service.
	# the user block
	OPTIONAL ?socialEvent dcns:creator ?user.
		OPTIONAL ?user sioc:account_of ?person.
		OPTIONAL ?person foaf:name ?realname.
		OPTIONAL ?person geo:location ?location .
		OPTIONAL ?person geo:lat ?lat .
		OPTIONAL ?person geo:long ?long .
		OPTIONAL ?user foaf:name ?username .
		OPTIONAL ?user dcns:identifier ?osnid .
		OPTIONAL ?user dcbs:language ?userlanguage .
		OPTIONAL ?person dcbs:language ?personlanguage .
		# OPTIONAL ?person time:timeZone ?persontimezone . # this might not be possible as a person is not an interval
		OPTIONAL ?user sioc:status ?description
		OPTIONAL ?user sioc:avatar ?useravatar
		# how do we deal with nSubscribers, nSubscriptions and nPostings ? Should we? Is this not inferred somehow?
		OPTIONAL ?user foaf:page ?website .
		OPTIONAL ?user sioc:link ?profile .
		OPTIONAL ?user tm:num_subscribers ?subscribers .
		OPTIONAL ?user tm:num_subscriptions ?subscriptions .
		OPTIONAL ?user tm:num_postings ?postings .
	OPTIONAL ?socialEvent sioc:link ?sourceURL
	OPTIONAL ?socialEvent sioc:content ?text
	OPTIONAL ?user tm:num_subscribers ?subscribers .
	OPTIONAL ?user tm:num_subscriptions ?subscriptions .
	OPTIONAL ?user tm:num_postings ?postings .

}