PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX sioct: <http://rdfs.org/sioc/types#>
PREFIX dcns: <http://purl.org/dc/elements/1.1/>
PREFIX dctermsns: <http://purl.org/dc/terzms/>
PREFIX dctypens: <http://purl.org/dc/dcmitype/>
PREFIX dcamns: <http://purl.org/dc/dcam/>
PREFIX tm: <http://www.trendminer-project.eu/ontology/>

SELECT *
WHERE {
	?socialEvent a sioc:Item.
	OPTIONAL ?socialEvent sioc:container ?service.
	OPTIONAL ?socialEvent sioc:links_to ?link
}