package org.openimaj.util.hash;

/**
 * {@link HashComposition}s are {@link HashFunction}s that compose the hash
 * codes generated by multiple hash functions applied to an object into a single
 * hash code for that object.
 * 
 * @author Jonathon Hare (jsh2@ecs.soton.ac.uk)
 * 
 * @param <OBJECT>
 *            Object being hashed
 */
public abstract class HashComposition<OBJECT> implements HashFunction<OBJECT> {
	protected HashFunction<OBJECT>[] hashFunctions;

	protected HashComposition(HashFunction<OBJECT>... functions) {
		this.hashFunctions = functions;
	}
}
