package org.openimaj.ml.clustering;

/**
 * Interface for clusterers capable of providing the centroids
 * of the clusters.
 * 
 * @author Jonathon Hare (jsh2@ecs.soton.ac.uk)
 *
 * @param <DATATYPE> the primitive array datatype which represents a centroid of this cluster
 */
public interface CentroidsProvider<DATATYPE> {
	/**
	 * @return the centroids generated by the clustering
	 */
	public abstract DATATYPE[] getCentroids();
}
