#!/bin/bash

# A simple shell script to run the GlobalFeaturesTool
#
# @author Jonathon Hare

bin=`dirname "$0"`

java -Xmx2G -Djava.awt.headless=true -jar "$bin/target/GlobalFeaturesTool.jar" ${1+"$@"}
