#!/bin/bash

# A simple shell script to run the ParallelExecutor tool
#
# @author Jonathon Hare

bin=`dirname "$0"`

java -Xmx8G -Djava.awt.headless=true -classpath $CLASSPATH:"$bin/target/GlobalFeaturesTool.jar" org.openimaj.tools.globalfeature.ParallelExecutor ${1+"$@"}